version: '3'

services:
   db:
      image: mysql:8.0
      container_name: appsDB
      restart: always
      ports:
       - '6603:3306'
      environment:
        MYSQL_ROOT_PASSWORD: fiap2020
   app:
      depends_on:
       - db
      image: phpmyadmin/phpmyadmin
      container_name: phpmyadmin
      restart: always
      ports:
       - '8080:80'
      environment:
        PMA_HOST: db
   rabbitmq:
      image: rabbitmq:3-management
      ports:
       - "5672:5672"
       - "15672:15672"
      container_name: rabbitmq
      hostname: netflix-rabbit     
